# Generated by Django 4.0 on 2021-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cost', models.IntegerField(default=0)),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
    ]
