# Generated by Django 4.0 on 2021-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('payment', models.DateTimeField(auto_now_add=True)),
                ('last_use', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
