# Generated by Django 4.0 on 2021-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_payment_user_credit_user_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
