# Generated by Django 4.0 on 2021-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_create_alter_user_credit_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
